name: "together_listen"
description: "A new Flutter project."

version: 1.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter_web: ^0.2.2+1
  webview_flutter: ^4.0.0
  webview_flutter_android: ^4.3.2 # 新增Android实现包
  webview_flutter_wkwebview: ^3.3.0 
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
